// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/checkpoint.proto

package com.embulk.input.pubsub.checkpoint;

public final class CheckpointProtos {
  private CheckpointProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckpointContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckpointContent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src/main/resources/checkpoint.proto\032(g" +
      "oogleapis/google/pubsub/v1/pubsub.proto\"" +
      "F\n\021CheckpointContent\0221\n\010messages\030\001 \003(\0132\037" +
      ".google.pubsub.v1.PubsubMessageB8\n\"com.e" +
      "mbulk.input.pubsub.checkpointB\020Checkpoin" +
      "tProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.pubsub.v1.PubsubProto.getDescriptor(),
        }, assigner);
    internal_static_CheckpointContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CheckpointContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckpointContent_descriptor,
        new java.lang.String[] { "Messages", });
    com.google.pubsub.v1.PubsubProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
